[server]
name = "sky.example"

[server.http]
addr = ":7030"

[server.pprof]
addr = ":7031"

[server.metrics.prometheus]
addr = ":7032"
disableHTTPRequestsTotalCounter = false
disableHTTPRequestsDurationHistogram = false
disableHTTPRequestsDurationSummary = true

[server.log]
level = "info"
#development = true

[[redis]]
name = "rdb"
host = "127.0.0.1"
port = 6379

[[elasticsearch]]
name = "es"
addrs = ["http://localhost:9200"]
username = ""
password = ""

[[database]]
name = "db"
host = "127.0.0.1"
port = 3306
db = "test"
user = "root"
pass = "123456"

[[client]]
name = "sky.helloworld"
protocol = "http"
host = "localhost:7020"